version: '3'
services:
  postgres:
    image: "kartoza/postgis"
    restart: always
    container_name: "postgis_pondionstracker"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pondionstracker
      - POSTGRES_USER=pondionstracker
      - POSTGRES_PASSWORD=pondionstracker
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
